name: Generate Snake

on:
  schedule: # Runs every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: bhumi110
          outputs:
              dist/snake-neon.svg?color_snake=39FF14&color_dots=#FF00FF,#39FF14,#00FFFF,#FF1493,#FFD700


      - name: Push snake files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
